version: 2
updates:
  # GitHub Actions Dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gh-deps:
        patterns:
          - "*"
  # Dart Dependencies
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dart-deps:
        patterns:
          - "*"
  # NPM Dependencies
  - package-ecosystem: "npm"
    directory: "/extensions/vscode"
    schedule:
      interval: "weekly"
    ignore:
      # Updating @types/vscode requires unnecessarily bumping the VS Code engine version, see:
      # https://github.com/dart-frog-dev/dart_frog/issues/1033
      - dependency-name: "@types/vscode"
    groups:
      npm-deps:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "weekly"
    groups:
      npm-deps:
        patterns:
          - "*"
