version: 2
updates:
  # GitHub Actions Dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      gh-deps:
        patterns:
          - "*"
  # NPM Dependencies
  - package-ecosystem: "npm"
    directory: "/extensions/vscode"
    schedule:
      interval: "monthly"
    ignore:
      # Updating @types/vscode requires unnecessarily bumping the VS Code engine version, see:
      # https://github.com/dart-frog-dev/dart_frog/issues/1033
      - dependency-name: "@types/vscode"
    groups:
      npm-deps:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "monthly"
    groups:
      npm-deps:
        patterns:
          - "*"
  # Dart Dependencies
  - package-ecosystem: pub
    directory: /packages/dart_frog
    schedule:
      interval: monthly
    groups:
      packages-dart-frog-pub:
        patterns:
          - "*"
  - package-ecosystem: pub
    directory: /packages/dart_frog_auth
    schedule:
      interval: monthly
    groups:
      packages-dart-frog-auth-pub:
        patterns:
          - "*"
  - package-ecosystem: pub
    directory: /packages/dart_frog_cli/e2e
    schedule:
      interval: monthly
    groups:
      packages-dart-frog-cli-e2e-pub:
        patterns:
          - "*"
  - package-ecosystem: pub
    directory: /packages/dart_frog_cli
    schedule:
      interval: monthly
    groups:
      packages-dart-frog-cli-pub:
        patterns:
          - "*"
  - package-ecosystem: pub
    directory: /packages/dart_frog_gen
    schedule:
      interval: monthly
    groups:
      packages-dart-frog-gen-pub:
        patterns:
          - "*"
  - package-ecosystem: pub
    directory: /packages/dart_frog_lint
    schedule:
      interval: monthly
    groups:
      packages-dart-frog-lint-pub:
        patterns:
          - "*"
  - package-ecosystem: pub
    directory: /packages/dart_frog_test/example
    schedule:
      interval: monthly
    groups:
      packages-dart-frog-test-example-pub:
        patterns:
          - "*"
  - package-ecosystem: pub
    directory: /packages/dart_frog_test
    schedule:
      interval: monthly
    groups:
      packages-dart-frog-test-pub:
        patterns:
          - "*"
  - package-ecosystem: pub
    directory: /packages/dart_frog_web_socket
    schedule:
      interval: monthly
    groups:
      packages-dart-frog-web-socket-pub:
        patterns:
          - "*"
