name: dart_frog_gen
description: Code generation tooling for Dart Frog — a fast, minimalistic backend framework for Dart.
version: 2.0.2
homepage: https://dart-frog.dev
repository: https://github.com/dart-frog-dev/dart_frog
issue_tracker: https://github.com/dart-frog-dev/dart_frog/issues
documentation: https://dart-frog.dev/getting-started
topics: [server, backend, dart-frog, codegen]

screenshots:
  - description: "Dart Frog logo."
    path: assets/logo.png

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  path: ^1.8.1
  pubspec_parse: ^1.2.2

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
