name: dart_frog_auth
description: The official authentication library for Dart Frog — a fast, minimalistic backend framework for Dart.
version: 1.2.2
homepage: https://dart-frog.dev
repository: https://github.com/dart-frog-dev/dart_frog
issue_tracker: https://github.com/dart-frog-dev/dart_frog/issues
documentation: https://dart-frog.dev/getting-started
topics: [server, backend, dart-frog, authentication, middleware]

screenshots:
  - description: "Dart Frog logo."
    path: assets/logo.png

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
