name: dart_frog_auth
description: Header authentication based middlewares for Dart Frog. Built by Very Good Ventures.
version: 1.2.1
homepage: https://dart-frog.dev
repository: https://github.com/dart-frog-dev/dart_frog
issue_tracker: https://github.com/dart-frog-dev/dart_frog/issues
documentation: https://dart-frog.dev/getting-started
topics: [server, backend, dart-frog, authentication, middleware]

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^9.0.0
