include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - lib/src/version.dart
linter:
  rules:
    # Experimental and there are lots of false positives
    specify_nonobvious_property_types: false
