name: dart_frog_test
description: A testing library which makes it easy to test Dart frog services.
version: 0.1.1
homepage: https://dart-frog.dev
repository: https://github.com/dart-frog-dev/dart_frog
issue_tracker: https://github.com/dart-frog-dev/dart_frog/issues
documentation: https://dart-frog.dev/getting-started
topics: [server, backend, dart-frog, test]

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0
  matcher: ^0.12.16
  meta: ^1.9.1
  mocktail: ^1.0.0
  test: ^1.19.2

