name: publish/dart_frog_web_socket

on:
  push:
    tags:
      - "dart_frog_web_socket-v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    environment: pub.dev
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for authentication using OIDC

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v5

      - name: 📦 Publish
        uses: ./.github/actions/pub_publish
        with:
          working_directory: packages/dart_frog_web_socket
