name: update_cli_bundles

on:
  schedule:
    # weekly on mondays at 8 am utc
    - cron: "0 8 * * 1"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: dart-lang/setup-dart@v1

      - name: Install mason
        run: dart pub global activate mason_cli

      - name: Bump templates
        run: tool/generate_bundles.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7.0.8
        with:
          base: main
          branch: feat/bump-template-bundles
          commit-message: "feat: update cli bundles"
          title: "feat(dart_frog_cli): update cli bundles"
          body: Please squash and merge me!
          labels: bot
